/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as DisasterRouteImport } from './routes/disaster'
import { Route as BasesRouteImport } from './routes/bases'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPlanesRouteImport } from './routes/api/planes'
import { Route as ApiPublicHooksSweepCamerasRouteImport } from './routes/api/public/hooks/sweep-cameras'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const DisasterRoute = DisasterRouteImport.update({
  id: '/disaster',
  path: '/disaster',
  getParentRoute: () => rootRouteImport,
} as any)
const BasesRoute = BasesRouteImport.update({
  id: '/bases',
  path: '/bases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanesRoute = ApiPlanesRouteImport.update({
  id: '/api/planes',
  path: '/api/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSweepCamerasRoute =
  ApiPublicHooksSweepCamerasRouteImport.update({
    id: '/api/public/hooks/sweep-cameras',
    path: '/api/public/hooks/sweep-cameras',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bases': typeof BasesRoute
  '/disaster': typeof DisasterRoute
  '/fleet': typeof FleetRoute
  '/incidents': typeof IncidentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/planes': typeof ApiPlanesRoute
  '/api/public/hooks/sweep-cameras': typeof ApiPublicHooksSweepCamerasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bases': typeof BasesRoute
  '/disaster': typeof DisasterRoute
  '/fleet': typeof FleetRoute
  '/incidents': typeof IncidentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/planes': typeof ApiPlanesRoute
  '/api/public/hooks/sweep-cameras': typeof ApiPublicHooksSweepCamerasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bases': typeof BasesRoute
  '/disaster': typeof DisasterRoute
  '/fleet': typeof FleetRoute
  '/incidents': typeof IncidentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/planes': typeof ApiPlanesRoute
  '/api/public/hooks/sweep-cameras': typeof ApiPublicHooksSweepCamerasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bases'
    | '/disaster'
    | '/fleet'
    | '/incidents'
    | '/reports'
    | '/settings'
    | '/api/planes'
    | '/api/public/hooks/sweep-cameras'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bases'
    | '/disaster'
    | '/fleet'
    | '/incidents'
    | '/reports'
    | '/settings'
    | '/api/planes'
    | '/api/public/hooks/sweep-cameras'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bases'
    | '/disaster'
    | '/fleet'
    | '/incidents'
    | '/reports'
    | '/settings'
    | '/api/planes'
    | '/api/public/hooks/sweep-cameras'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BasesRoute: typeof BasesRoute
  DisasterRoute: typeof DisasterRoute
  FleetRoute: typeof FleetRoute
  IncidentsRoute: typeof IncidentsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ApiPlanesRoute: typeof ApiPlanesRoute
  ApiPublicHooksSweepCamerasRoute: typeof ApiPublicHooksSweepCamerasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disaster': {
      id: '/disaster'
      path: '/disaster'
      fullPath: '/disaster'
      preLoaderRoute: typeof DisasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bases': {
      id: '/bases'
      path: '/bases'
      fullPath: '/bases'
      preLoaderRoute: typeof BasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/planes': {
      id: '/api/planes'
      path: '/api/planes'
      fullPath: '/api/planes'
      preLoaderRoute: typeof ApiPlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sweep-cameras': {
      id: '/api/public/hooks/sweep-cameras'
      path: '/api/public/hooks/sweep-cameras'
      fullPath: '/api/public/hooks/sweep-cameras'
      preLoaderRoute: typeof ApiPublicHooksSweepCamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BasesRoute: BasesRoute,
  DisasterRoute: DisasterRoute,
  FleetRoute: FleetRoute,
  IncidentsRoute: IncidentsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ApiPlanesRoute: ApiPlanesRoute,
  ApiPublicHooksSweepCamerasRoute: ApiPublicHooksSweepCamerasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
