/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DisasterRouteImport } from './routes/disaster'
import { Route as CitationsRouteImport } from './routes/citations'
import { Route as CamerasRouteImport } from './routes/cameras'
import { Route as BoloRouteImport } from './routes/bolo'
import { Route as BasesRouteImport } from './routes/bases'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DispatchUnitsRouteImport } from './routes/dispatch.units'
import { Route as ApiPlanesRouteImport } from './routes/api/planes'
import { Route as ApiPublicHooksSweepCamerasRouteImport } from './routes/api/public/hooks/sweep-cameras'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DisasterRoute = DisasterRouteImport.update({
  id: '/disaster',
  path: '/disaster',
  getParentRoute: () => rootRouteImport,
} as any)
const CitationsRoute = CitationsRouteImport.update({
  id: '/citations',
  path: '/citations',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasRoute = CamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => rootRouteImport,
} as any)
const BoloRoute = BoloRouteImport.update({
  id: '/bolo',
  path: '/bolo',
  getParentRoute: () => rootRouteImport,
} as any)
const BasesRoute = BasesRouteImport.update({
  id: '/bases',
  path: '/bases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchUnitsRoute = DispatchUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => DispatchRoute,
} as any)
const ApiPlanesRoute = ApiPlanesRouteImport.update({
  id: '/api/planes',
  path: '/api/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSweepCamerasRoute =
  ApiPublicHooksSweepCamerasRouteImport.update({
    id: '/api/public/hooks/sweep-cameras',
    path: '/api/public/hooks/sweep-cameras',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/bases': typeof BasesRoute
  '/bolo': typeof BoloRoute
  '/cameras': typeof CamerasRoute
  '/citations': typeof CitationsRoute
  '/disaster': typeof DisasterRoute
  '/dispatch': typeof DispatchRouteWithChildren
  '/fleet': typeof FleetRoute
  '/incidents': typeof IncidentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/planes': typeof ApiPlanesRoute
  '/dispatch/units': typeof DispatchUnitsRoute
  '/api/public/hooks/sweep-cameras': typeof ApiPublicHooksSweepCamerasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/bases': typeof BasesRoute
  '/bolo': typeof BoloRoute
  '/cameras': typeof CamerasRoute
  '/citations': typeof CitationsRoute
  '/disaster': typeof DisasterRoute
  '/dispatch': typeof DispatchRouteWithChildren
  '/fleet': typeof FleetRoute
  '/incidents': typeof IncidentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/planes': typeof ApiPlanesRoute
  '/dispatch/units': typeof DispatchUnitsRoute
  '/api/public/hooks/sweep-cameras': typeof ApiPublicHooksSweepCamerasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/bases': typeof BasesRoute
  '/bolo': typeof BoloRoute
  '/cameras': typeof CamerasRoute
  '/citations': typeof CitationsRoute
  '/disaster': typeof DisasterRoute
  '/dispatch': typeof DispatchRouteWithChildren
  '/fleet': typeof FleetRoute
  '/incidents': typeof IncidentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/planes': typeof ApiPlanesRoute
  '/dispatch/units': typeof DispatchUnitsRoute
  '/api/public/hooks/sweep-cameras': typeof ApiPublicHooksSweepCamerasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/bases'
    | '/bolo'
    | '/cameras'
    | '/citations'
    | '/disaster'
    | '/dispatch'
    | '/fleet'
    | '/incidents'
    | '/reports'
    | '/settings'
    | '/api/planes'
    | '/dispatch/units'
    | '/api/public/hooks/sweep-cameras'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/bases'
    | '/bolo'
    | '/cameras'
    | '/citations'
    | '/disaster'
    | '/dispatch'
    | '/fleet'
    | '/incidents'
    | '/reports'
    | '/settings'
    | '/api/planes'
    | '/dispatch/units'
    | '/api/public/hooks/sweep-cameras'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/bases'
    | '/bolo'
    | '/cameras'
    | '/citations'
    | '/disaster'
    | '/dispatch'
    | '/fleet'
    | '/incidents'
    | '/reports'
    | '/settings'
    | '/api/planes'
    | '/dispatch/units'
    | '/api/public/hooks/sweep-cameras'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  BasesRoute: typeof BasesRoute
  BoloRoute: typeof BoloRoute
  CamerasRoute: typeof CamerasRoute
  CitationsRoute: typeof CitationsRoute
  DisasterRoute: typeof DisasterRoute
  DispatchRoute: typeof DispatchRouteWithChildren
  FleetRoute: typeof FleetRoute
  IncidentsRoute: typeof IncidentsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ApiPlanesRoute: typeof ApiPlanesRoute
  ApiPublicHooksSweepCamerasRoute: typeof ApiPublicHooksSweepCamerasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disaster': {
      id: '/disaster'
      path: '/disaster'
      fullPath: '/disaster'
      preLoaderRoute: typeof DisasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citations': {
      id: '/citations'
      path: '/citations'
      fullPath: '/citations'
      preLoaderRoute: typeof CitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras': {
      id: '/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof CamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolo': {
      id: '/bolo'
      path: '/bolo'
      fullPath: '/bolo'
      preLoaderRoute: typeof BoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bases': {
      id: '/bases'
      path: '/bases'
      fullPath: '/bases'
      preLoaderRoute: typeof BasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch/units': {
      id: '/dispatch/units'
      path: '/units'
      fullPath: '/dispatch/units'
      preLoaderRoute: typeof DispatchUnitsRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/api/planes': {
      id: '/api/planes'
      path: '/api/planes'
      fullPath: '/api/planes'
      preLoaderRoute: typeof ApiPlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sweep-cameras': {
      id: '/api/public/hooks/sweep-cameras'
      path: '/api/public/hooks/sweep-cameras'
      fullPath: '/api/public/hooks/sweep-cameras'
      preLoaderRoute: typeof ApiPublicHooksSweepCamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DispatchRouteChildren {
  DispatchUnitsRoute: typeof DispatchUnitsRoute
}

const DispatchRouteChildren: DispatchRouteChildren = {
  DispatchUnitsRoute: DispatchUnitsRoute,
}

const DispatchRouteWithChildren = DispatchRoute._addFileChildren(
  DispatchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  BasesRoute: BasesRoute,
  BoloRoute: BoloRoute,
  CamerasRoute: CamerasRoute,
  CitationsRoute: CitationsRoute,
  DisasterRoute: DisasterRoute,
  DispatchRoute: DispatchRouteWithChildren,
  FleetRoute: FleetRoute,
  IncidentsRoute: IncidentsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ApiPlanesRoute: ApiPlanesRoute,
  ApiPublicHooksSweepCamerasRoute: ApiPublicHooksSweepCamerasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
